In [2]:
from sentence_transformers import SentenceTransformer

#1. Load a pretrained Sentence Transformers model
model=SentenceTransformer("all-MiniLM-L6-v2")



In [4]:
import numpy as np

In [7]:
#The idea is suppose we have a document like this
doc=["Hi This is Akshar and i'm an associate software enginner",
     "I have been work as a full stack python developer",
    ]

#Now we want to convert this doc into a numerical representation i.e vector embeddings

In [9]:
#We can calculate the embeddings using model.encode()
embeddings=model.encode(doc)
print(f"This is the vector embedding{embeddings}")
print(embeddings.shape)  #(2,384)


This is the vector embedding[[-9.96815562e-02 -3.27915922e-02 -2.03487594e-02 -3.80280577e-02
   5.01078274e-03 -4.39491309e-02  4.06713933e-02  2.15435103e-02
  -1.61135271e-02 -1.79011971e-02 -2.87030395e-02 -4.26244847e-02
   3.47928740e-02 -2.76271403e-02  2.13619284e-02 -4.89108218e-03
  -1.00778535e-01 -1.06605683e-02 -3.48562375e-02 -1.03249513e-01
  -3.22721004e-02 -3.62719148e-02 -5.83184659e-02 -4.10062484e-02
   9.29938033e-02 -5.33070862e-02  8.93358365e-02  4.96856496e-03
   2.59022061e-02 -2.64441986e-02  1.18377842e-02 -9.09537822e-02
   7.26488084e-02  2.33002566e-02  4.06675460e-03  9.95928794e-02
  -1.03627384e-01  2.12178025e-02 -4.10345122e-02 -4.45006490e-02
  -7.40882158e-02 -2.77931765e-02 -2.25179978e-02 -8.29176679e-02
   1.70271005e-02 -5.88383712e-02 -4.32913378e-02 -6.97692856e-02
   6.69591650e-02  5.90903908e-02 -9.32664052e-02 -6.73168376e-02
   9.74996574e-03 -3.75071019e-02  3.99893969e-02 -1.08321186e-03
   1.04040792e-02  1.85050424e-02 -1.68539509e-0

In [12]:
print(doc)
splitted_docs=doc[0].split()
print(splitted_docs)

["Hi This is Akshar and i'm an associate software enginner", 'I have been work as a full stack python developer']
['Hi', 'This', 'is', 'Akshar', 'and', "i'm", 'an', 'associate', 'software', 'enginner']


In [13]:
test1_doc=["The dog jumped over the cat"]
test2_doc=["The cat jumped over the dog"]



In [17]:
test1_embeddings=model.encode(test1_doc)
test2_embeddings=model.encode(test2_doc)

#Now we will compare to actually see how similar they are 


In [19]:
#Lets see similarity between same embeddings
model.similarity(test1_embeddings,test1_embeddings)

#It will give tensor(1) that means they are exactly similar

tensor([[1.0000]])

In [21]:
#Lets see similarity between test1_embeddings and test2_embeddings
model.similarity(test1_embeddings,test2_embeddings)

#It gave 98 percent match

tensor([[0.9895]])

In [27]:
#Suppose we have a document and a query and we have to give the similarity of the query to the document
document=["mera naam hai akshar","mera dost hai akshat"]
embedding=model.encode(document)
print(embedding)
embedding.shape
query="my name is akshar"

[[-2.95475423e-02  1.16983555e-01  1.41736064e-02 -4.05559922e-03
   1.86934043e-02  6.19398579e-02  1.11865573e-01 -7.32963830e-02
   8.02727118e-02  1.08961540e-03  1.09524958e-01 -7.73820579e-02
   6.21952582e-03 -5.49531989e-02  6.73907697e-02 -6.95038820e-03
  -3.58068794e-02 -2.49463469e-02 -3.30882855e-02 -4.80401888e-02
  -4.26459610e-02  8.72965902e-02 -5.83399348e-02  1.83530040e-02
  -3.96906324e-02 -1.88963600e-02  6.35460094e-02 -1.46632073e-02
  -3.01775020e-02 -6.90580718e-03  6.54301867e-02  1.44399498e-02
  -1.94701310e-02  5.85938692e-02 -8.66501406e-03  7.31368437e-02
  -1.07033901e-01 -2.00555008e-02  1.52372345e-02 -4.01262715e-02
   3.72966938e-02 -3.92682403e-02  2.12185504e-03 -1.25739142e-01
   4.30713147e-02 -3.88913117e-02  7.59275025e-03 -3.29140797e-02
   8.11862722e-02  1.40691577e-02 -1.10128321e-01 -1.48704629e-02
  -3.41067724e-02 -5.17075583e-02  5.72877452e-02 -4.84102033e-03
  -2.92979293e-02 -4.70514633e-02 -8.49816296e-03 -1.47478646e-02
  -4.71932

In [29]:
model.similarity(embedding, model.encode(query))

tensor([[0.4820],
        [0.3794]])